name: HW0 - Integer Power

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & run programme
        run: make -C '0. Integer Power' all
      - name: Run programme
        run: cd '0. Integer Power' && ./power
