name: HW1 - Sorting & Top-Down Splay Trees

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build programme
        run: make -C '1. Sorting & Top-Down Splay Trees' all
      - name: Run Sort
        run: cd '1. Sorting & Top-Down Splay Trees' && ./sort
      - name: Run Top-Down Splay Trees
        run: cd '1. Sorting & Top-Down Splay Trees' && ./topdownsplay
